modLoader="javafml" #mandatory
loaderVersion="[49,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="Apache Public License v2"
[[mods]] #mandatory
modId="westerosblocks" #mandatory
version="${version}" #mandatory
displayName="WesterosBlocks" #mandatory
displayURL="https://www.westeroscraft.com/" #optional
# A file name (in the root of the mod JAR) containing a logo for display
logoFile="westerosblocks.jpg" #optional
# A text field displayed in the mod UI
authors="mikeprimm, Thamus_Knoward, Emoticone11" #optional
credits="Design and code by mikeprimm, artwork and block design by Thamus_Knoward, Emoticone11"
description='''
This mod provides the custom blocks needed by WesterosCraft (www.westeroscraft.com)
'''
[[dependencies.westerosblocks]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[49,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.westerosblocks]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20,)"
    ordering="NONE"
    side="BOTH"
